task 6
Bokbulbok7/nc-news pull request #7
Opened 2023-11-21 15:52 UTC by Bokbulbok7

2023-11-21 16:11 UTC, Hard-Luck requested changes
Needs another test, them you can merge

2023-11-21 16:11 UTC, Hard-Luck commented on __tests__/integration.test.js
> +            article_id: expect.any(Number),
You know the article id

2023-11-21 16:11 UTC, Hard-Luck commented on __tests__/integration.test.js
> +});
Need to check comments are sorted by date

2023-11-22 08:35 UTC, popatre approved these changes
Looks good, just remove that console log 👍

2023-11-22 08:35 UTC, popatre commented on __tests__/integration.test.js
> +          console.log(comment);
remove console log

2023-11-22 08:35 UTC, popatre commented on __tests__/integration.test.js
> +      });
nice jest sorted test 👍

2023-11-22 08:47 UTC, merged